### ISSUE TITLE
Multiple Attachments?

### ISSUE THREAD

**Issue by chrismbeckett** [Kinto/kinto-attachment#49]
Why can't a record have multiple attachments?

**Comment by Natim** [comment]
Because then it adds a level of synchronisation and it make its usage more complex.

What is your use case for multiple file attachment with Kinto?

**Comment by chrismbeckett** [comment]
I am developing property management software, and a record can reflect a local amenity, a household, etc. Users want to be able to attach multiple files to these things to supplement the data.  There are a lot of use cases in business software where multiple attachments would be a requirement.

**Comment by Natim** [comment]
Then you probably want to create a bucket per local amenity and an attachment collection to it so that you can upload multiple attachment to it. You will probably also have a contract collection and other collection like the prospects or the people to contact regarding the property etc.

**Comment by chrismbeckett** [comment]
Groups can't be shared across buckets - that would kill my security model? I get the point. This plugin is more about making "a record" into "an attachment", but then reference linking to other records.

Any reason not to just use a 'type' property on my records and store them in the same collection. For example I could have records with type "property", "property_file", and "property_comment" all in the same collection?

**Comment by Natim** [comment]
> Groups can't be shared across buckets

You are right. You can also have a bucket for your app and multiple collections in it. You can also have a property collection in it that would link collections altogether. (property_files, property_comment, etc)

> Any reason not to just use a 'type' property on my records and store them in the same collection. For example I could have records with type "property", "property_file", and "property_comment" all in the same collection?

You can probably also just do that and use filtering to get only the records you are looking for.
Right now I can see any reason why it wouldn't work.

I think for better permissions management I would go for the former because you won't be able to filter permission per type.

**Comment by chrismbeckett** [comment]
OK, I got it :) Thank you for your suggestions. With reference linking I can use whatever strategy I want that fits my security and query/filter requirements. I can make that work.

**Comment by Natim** [comment]
Related to: https://github.com/mozilla-services/react-jsonschema-form/pull/193

**Comment by geomapdev** [comment]
Are there any plans to support the react-jsonschema-form file widget in kinto-attachment? This would be a nice feature, but if it's not on the roadmap I can follow your suggestions above.  Thanks!

**Comment by Natim** [comment]
I think we already have kinto-attachment support in the Kinto admin (the kinto-admin uses react-jsonschema-form but I'm not sure it does for the kinto-attachment feature).

**Comment by geomapdev** [comment]
yes, the attachment feature works well in kinto-admin. I've tested with S3 bucket and have that working. I'd like to be able to embed attachments into the JSON schema, so they're able to be used like any other type of field. This renders the file widgets in kinto-admin, and i can upload and submit the form, but the attachments aren't saving anywhere:

JSON Schema:
{
  "type": "object",
  "properties": {
    "file": {
      "title": "Single File",
      "type": "string"
    },
    "files": {
      "title": "Multiple files",
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  }
}
UI Schema:
{
  "file": {
    "ui:widget": "file"
  },
  "files": {
    "ui:widget": "files"
  }
}

**Comment by Natim** [comment]
This seems really interesting. I guess you need to catch the content of the field and make the necessary form/multipart POST calls and then use the kinto-http.js client to add attachments.

https://github.com/Kinto/kinto-admin/blob/master/src/sagas/collection.js#L159-L164

**Comment by glasserc** [comment]
Just to clarify, no, I'm not aware of any roadmap items to support files better in the kinto admin.
