### ISSUE TITLE
Add a SeaFile backend.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-attachment#52]
- http://manual.seafile.com/develop/web_api.html#share
- https://pypi.python.org/pypi/seafileapi/0.1.1

While deploying to heroku @enguerran was struggleling to find a good option for serving files.

**Comment by enguerran** [comment]
Thank you for referencing this issue.
In fact @ticabri is an organization for my ex publication. My github account is @enguerran.

**Comment by enguerran** [comment]
The seafile Web API is easy to start with : http://manual.seafile.com/develop/web_api.html#quick-start

```
http https://cloud.seafile.com/api2/ping/

"pong"
```

To get a token:
```
echo '{"username": "username@example.com", "password": "123456"}' | http https://cloud.seafile.com/api2/auth-token/

{"token": "24fd3c026886e3121b2ca630805ed425c272cb96"}
```

auth ping:
```
http https://cloud.seafile.com/api2/auth/ping/ "Authorization: token 24fd3c026886e3121b2ca630805ed425c272cb96"

"pong"
```

**Comment by Natim** [comment]
@enguerran Do you know how long a token is valid for? Can we put it in the config?

**Comment by enguerran** [comment]
I don't know yet, I need to make some research.

I generated a token at 2 pm and it is still active, I will try tomorrow. As I cannot find the information on seafile website.

**Comment by enguerran** [comment]
I resend the same request with the exact same token. I can be affirmative: the token is valid for at least 24 hours.

Anyway, the seafileapi seams to work with user/password as described here: https://github.com/haiwen/python-seafile/blob/554a7b606fc59f926f0c1e79fecc78b58cde3bf0/tests/fixtures.py

**Comment by leplatrem** [comment]
I'm closing this. 

Please reopen if you think it's still a thing ;)
