### ISSUE TITLE
Document release process to PyPI

### ISSUE THREAD

**Issue by grahamalama** [Kinto/kinto-attachment#617]

**Comment by Natim** [comment]
We usually use [the same process that we use for Kinto.](https://docs.kinto-storage.org/en/latest/community.html#how-to-release)

1. We create a pull request with the changelog and we use the `prerelease` command of [zest.releaser](https://pypi.org/project/zest.releaser/) to update the version number
2. Once merge with use the `release` to build the wheel
3. Then we use the `postrelease` to upload it to PyPI
