### ISSUE TITLE
What is the best way to store file thumbnails using kinto-attachment?

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-attachment#64]
I would like to store both a picture and its thumbnail in kinto-attachment.
Shall I create two collections ``gallery`` and ``gallery_thumbnails``?

How can I store both files in the same collection/record?

**Comment by leplatrem** [comment]
You can embed the thumbnail in the JPG metadata :)

You can store them in two collections and share the same record ids. This way when you reach the *detail* page, you can query the single record containing the full image directly.

**Comment by Natim** [comment]
> You can embed the thumbnail in the JPG metadata :)

This doesn't help because the goal is to load thumbnails first and then the picture. To be able to read the thumbnail from the metadata I would need to have downloaded the picture first.

> You can store them in two collections and share the same record ids. This way when you reach the detail page, you can query the single record containing the full image directly.

I like this solution.
