### ISSUE TITLE
What is the best way to store encrypted files with Kinto-attachment?

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-attachment#67]
@jadjay is looking for a way to build a file sharing API that let user share encrypted files as part as the [C.H.A.T.O.N.S](http://framablog.org/2016/02/09/chatons-le-collectif-anti-gafam/) framasoft project.

How will you do that with Kinto and Kinto-Attachment?

**Comment by almet** [comment]
I would do it as follows:

1. Encrypt the file on the client side,
2. Get the resulting encrypted file
3. Upload it to kinto
4. Share a link containing the secret
5. The link would load an application that would be able to decrypt the data using the secret.

So, I think it would be an application built on top of kinto, but nothing needs to be present in kinto-attachment itself.
