### ISSUE TITLE
Add an option not to prepend the base_url in the record location.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-attachment#73]
- [ ] We want to be able to have related file path to the base_url in records (It should be the default according to #24)
- [ ] We want to have the base_url in the Hello view.

**Comment by leplatrem** [comment]
What is the use-case ?

**Comment by Natim** [comment]
The first use case is for Fennec OTA where we do not want the base_url in records but we want it in the Hello page. Related to [Bug 1257882](https://bugzilla.mozilla.org/show_bug.cgi?id=1257882#c2

**Comment by almet** [comment]
I'm not sure it should be the default behaviour, though: it seems easier to have the complete URL of the attachment in the record (no additional operation on the client side, everything can be done with one request).

**Comment by Natim** [comment]
The reason why I was suggesting it to be the default behavior is to solve the #24 issue which make is complicated to change the base_url with existing records.

**Comment by almet** [comment]
I understand, thanks for pointing that out.

I would prefer to stick with the full URL in the records and for instance a script which updates all the records in case the `base_url` is updated, as I believe it's a good thing to focus on ease of use of our APIs rather than one-time processes like the change of a setting.

Such script would iterate over all the records in the database, looking for the `attachment.location` key, and would substitute the old value with the new one.

Would that solve your problem?

**Comment by Natim** [comment]
> I would prefer to stick with the full URL in the records and for instance a script which updates all the records in case the base_url is updated, as I believe it's a good thing to focus on ease of use of our APIs rather than one-time processes like the change of a setting.

The problem with that is that you will update the last_modified value of records where the data didn't changed except in the case where the url is actually the data you want to be notified about.

But in most cases you only want to update the record if the file data changed. That's at least the case in the Fennec OTA case.

In any case if we can handle both case with configuration it doesn't matter to me which one is the default one. I genuinely though that people that need to have the full url will know it and that people that are fine with both we be less likely to have the update location problem.

**Comment by almet** [comment]
So we would have two scenarii when want to update the `base_url`:

1. You set `prepend_base_url=True` (default) in the configuration: a script can iterate on records and update their values *and* `last_modified` field;
2. You set `prepend_base_url=False`, you need to tell your client to change the `base_url`. I'm not sure how you detect this on the client side and what should be done then.

Note that I'm not advocating against the idea of removing the `base_url` from the records. I think it's a good thing to do in some cases. I just thing that this shouldn't be the default behaviour.

**Comment by almet** [comment]
Also, this configuration should be exposed in the root URL and checked by the clients, otherwise they might fail without notice on configuration /server change.

It might also be a good idea to have this option setup by collection/bucket rather than having it server-wide.

**Comment by Natim** [comment]
> It might also be a good idea to have this option setup by collection/bucket rather than having it server-wide.

It can also be configured server-wide by bucket/collection as for kinto-signer.

However I don't see how it could be configured client-side because the server is responsible for putting the data there. So it should be the source of truth that tells where it puts the data.

**Comment by almet** [comment]
> I don't see how it could be configured client-side

That's not my proposal :) I was more proposing a configuration per collection, either in the configuration (like what we did for the signer) or in the bucket's data.
