### ISSUE TITLE
option to gzip uploaded file on the fly

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto-attachment#84]
Once we have the proper hooking mechanism in place - see https://github.com/Kinto/kinto/issues/677

We should offer the option to gzip files that are posted to Kinto, like how it's actually done for Fennec https://github.com/pocmo/Fennec-DLC-Catalog/blob/master/create_catalog.py#L136

That will let us use kinto-admin for managing fonts in Fennec

**Comment by tarekziade** [comment]
As discussed in a meeting, we're going to add the gzip option in kinto-attachment directly in the code for now

**Comment by almet** [comment]
Just to be sure I read this correctly: do you mean we should gzip the files once they're uploaded, so that it takes less space on the server?
